insert into vehicleclass (classname, brandname) values ('A1','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A3','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A3 Lim','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A3 SPB','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A3 e-tron','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A4 AVANT','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A4 Allroad','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A4L','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A5','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A6 Allroad','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A6 Avant','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A6 e-tron','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A6L','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A6L Hybrid','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A6L e-tron','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A6L(C8)','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A7','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A8L','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A8L 19年型 Plus','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('A8L Hybrid','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Audi e-tron','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('E-TRON','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('FBU-A3敞篷','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q2','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q2 e-tron','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q2L','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q2L e-tron','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q3','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q3 NF','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q5','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q5 Hybrid','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q5L','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q7','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q7 19 年型','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q7 45TFSI','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q7 55TFSI','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q7 e-tron','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('Q8','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('R8','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('RS3','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('RS4','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('RS5','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('RS6','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('RS7','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('S3','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('S4','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('S5','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('S6','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('S7','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('S8','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('SQ5','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('TT','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('TTRS','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('TTS','一汽奥迪');
insert into vehicleclass (classname, brandname) values ('新Q3','一汽奥迪');
